# Generated by Django 3.2.12 on 2022-08-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_conference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='injusred_reserved_list',
            new_name='injured_reserved_list',
        ),
    ]
