# Generated by Django 3.2.12 on 2022-08-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_rename_injusred_reserved_list_players_injured_reserved_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
